name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t saurabhkr38/myapp:${{ github.sha }} .

    - name: Login to Docker Hub
      run: echo "dckr_pat_RntOfEzuL0T421zA1O71P5aYv-I" | docker login -u saurabhkr38 --password-stdin

    - name: Push Docker image
      run: docker push saurabhkr38/myapp:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: kubectl set image deployment/myapp-deployment myapp=saurabhkr38/myapp:${{ github.sha }}

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

